import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/session_result.dart';
import '../theme/app_theme.dart';

class PdfScreen extends StatefulWidget {
  final SessionResult result;
  const PdfScreen({super.key, required this.result});

  @override
  State<PdfScreen> createState() => _PdfScreenState();
}

class _PdfScreenState extends State<PdfScreen> {
  bool _isGenerating = true;
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    _generatePdf();
  }

  Future<void> _generatePdf() async {
    final bytes = await _buildPdf(widget.result);
    setState(() {
      _pdfBytes     = bytes;
      _isGenerating = false;
    });
  }

  static Future<Uint8List> _buildPdf(SessionResult r) async {
    final pdf = pw.Document();

    // Colors
    final riskColor = _pdfRiskColor(r.riskLevel);
    final blue      = PdfColor.fromHex('#1565C0');
    final grey      = PdfColor.fromHex('#6B7280');
    final lightGrey = PdfColor.fromHex('#F5F7FA');
    final red       = PdfColor.fromHex('#D32F2F');
    final green     = PdfColor.fromHex('#2E7D32');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        build: (context) => [

          // ── Header ───────────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              color: blue,
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Sleep Apnea Screening Report',
                        style: pw.TextStyle(
                            fontSize: 18, fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white)),
                    pw.SizedBox(height: 4),
                    pw.Text('Generated by Sleep Apnea Screener App',
                        style: pw.TextStyle(
                            fontSize: 10, color: PdfColors.white)),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text('Date: ${_today()}',
                        style: pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                    pw.Text('Duration: ${r.totalDuration}',
                        style: pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 16),

          // ── Disclaimer ───────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#FFF8E1'),
              borderRadius: pw.BorderRadius.circular(6),
              border: pw.Border.all(color: PdfColor.fromHex('#FFE082')),
            ),
            child: pw.Text(
              '⚠ DISCLAIMER: This report is generated by an AI screening tool and is NOT a medical '
              'diagnosis. Please consult a certified sleep specialist for clinical evaluation.',
              style: pw.TextStyle(fontSize: 9, color: PdfColor.fromHex('#5D4037')),
            ),
          ),
          pw.SizedBox(height: 16),

          // ── Risk Summary ─────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: riskColor,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('RISK CLASSIFICATION',
                        style: pw.TextStyle(fontSize: 9,
                            color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
                    pw.Text(r.riskLevel.toUpperCase(),
                        style: pw.TextStyle(fontSize: 28,
                            color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
                    pw.Text('${r.ahiCategory} Sleep Apnea',
                        style: pw.TextStyle(fontSize: 12, color: PdfColors.white)),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text('AHI Score',
                        style: pw.TextStyle(fontSize: 9, color: PdfColors.white)),
                    pw.Text('${r.ahiEstimate}',
                        style: pw.TextStyle(fontSize: 28,
                            color: PdfColors.white, fontWeight: pw.FontWeight.bold)),
                    pw.Text('events / hour',
                        style: pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 16),

          // ── Metrics Table ─────────────────────────────────
          _sectionTitle('Clinical Metrics'),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColor.fromHex('#E0E0E0'), width: 0.5),
            children: [
              _tableHeader(['Metric', 'Value', 'Status'], blue),
              _tableRow('Average SpO2',      '${r.meanSpo2}%',
                  r.meanSpo2 >= 94 ? 'Normal' : 'Low', green, red, r.meanSpo2 >= 94),
              _tableRow('Minimum SpO2',      '${r.minSpo2}%',
                  r.minSpo2 >= 90 ? 'Normal' : 'Concern', green, red, r.minSpo2 >= 90),
              _tableRow('SpO2 < 90%',        '${r.minutesBelow90} minutes',
                  r.minutesBelow90 == 0 ? 'Normal' : 'Concern',
                  green, red, r.minutesBelow90 == 0),
              _tableRow('Average Heart Rate','${r.meanHr} bpm', '--', blue, blue, true),
              _tableRow('Avg RMSSD (HRV)',   '${r.meanRmssd} ms',
                  r.meanRmssd >= 20 ? 'Normal' : 'Low', green, red, r.meanRmssd >= 20),
              _tableRow('Avg SDNN (HRV)',    '${r.meanSdnn} ms',
                  r.meanSdnn >= 30 ? 'Normal' : 'Low', green, red, r.meanSdnn >= 30),
              _tableRow('Apnea Events',      '${r.apneaWindows} windows',
                  r.apneaWindows < 10 ? 'Low' : 'Elevated', green, red,
                  r.apneaWindows < 10),
              _tableRow('Longest Apnea Run', '${r.maxConsecutiveApnea} consecutive min',
                  r.maxConsecutiveApnea <= 3 ? 'Normal' : 'Elevated',
                  green, red, r.maxConsecutiveApnea <= 3),
            ],
          ),
          pw.SizedBox(height: 16),

          // ── AHI Reference ─────────────────────────────────
          _sectionTitle('AHI Reference Scale'),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: lightGrey,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _ahiRef('< 5',     'Normal',   PdfColor.fromHex('#2E7D32')),
                _ahiRef('5 – 14',  'Mild',     PdfColor.fromHex('#F57C00')),
                _ahiRef('15 – 29', 'Moderate', PdfColor.fromHex('#D32F2F')),
                _ahiRef('≥ 30',    'Severe',   PdfColor.fromHex('#7B1FA2')),
              ],
            ),
          ),
          pw.SizedBox(height: 16),

          // ── Recommendations ───────────────────────────────
          _sectionTitle('Recommendations'),
          pw.SizedBox(height: 8),
          ..._recommendations(r.riskLevel).map((rec) => pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 3),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('•  ', style: pw.TextStyle(color: blue, fontSize: 12)),
                pw.Expanded(
                  child: pw.Text(rec,
                      style: pw.TextStyle(fontSize: 10, color: PdfColors.black)),
                ),
              ],
            ),
          )),
          pw.SizedBox(height: 24),

          // ── Footer ────────────────────────────────────────
          pw.Divider(color: PdfColor.fromHex('#E0E0E0')),
          pw.SizedBox(height: 6),
          pw.Text(
            'This report was generated automatically by the Sleep Apnea Screener app. '
            'ML-based classification does not replace clinical polysomnography (PSG).',
            style: pw.TextStyle(fontSize: 8, color: grey),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _sectionTitle(String title) => pw.Text(
    title,
    style: pw.TextStyle(
        fontSize: 13, fontWeight: pw.FontWeight.bold,
        color: PdfColor.fromHex('#1A1A2E')),
  );

  static pw.TableRow _tableHeader(List<String> cols, PdfColor color) =>
    pw.TableRow(
      decoration: pw.BoxDecoration(color: color),
      children: cols.map((c) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 7),
        child: pw.Text(c,
            style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold,
                color: PdfColors.white)),
      )).toList(),
    );

  static pw.TableRow _tableRow(String metric, String value, String status,
      PdfColor okColor, PdfColor badColor, bool isOk) =>
    pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          child: pw.Text(metric, style: pw.TextStyle(fontSize: 9)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          child: pw.Text(value,
              style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          child: pw.Text(status,
              style: pw.TextStyle(
                  fontSize: 9, color: isOk ? okColor : badColor,
                  fontWeight: pw.FontWeight.bold)),
        ),
      ],
    );

  static pw.Widget _ahiRef(String range, String label, PdfColor color) =>
    pw.Column(children: [
      pw.Text(range,
          style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold,
              color: color)),
      pw.Text(label, style: pw.TextStyle(fontSize: 9, color: color)),
    ]);

  static PdfColor _pdfRiskColor(String risk) {
    switch (risk.toLowerCase()) {
      case 'low':      return PdfColor.fromHex('#2E7D32');
      case 'moderate': return PdfColor.fromHex('#F57C00');
      case 'high':     return PdfColor.fromHex('#D32F2F');
      case 'severe':   return PdfColor.fromHex('#7B1FA2');
      default:         return PdfColor.fromHex('#1565C0');
    }
  }

  static List<String> _recommendations(String risk) {
    final recs = [
      'Sleep on your side — back sleeping significantly worsens apnea events.',
      'Avoid alcohol and sedatives before bedtime.',
      'Maintain a consistent sleep schedule and bedroom temperature.',
      'Regular aerobic exercise can reduce apnea severity.',
    ];
    if (risk != 'Low') {
      recs.add('Schedule an appointment with a sleep specialist for formal evaluation.');
      recs.add('Consider undergoing in-lab polysomnography (PSG) for clinical confirmation.');
    }
    if (risk == 'High' || risk == 'Severe') {
      recs.add('Ask your doctor about CPAP therapy — the gold standard treatment for OSA.');
    }
    return recs;
  }

  static String _today() {
    final now = DateTime.now();
    return '${now.day}/${now.month}/${now.year}';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PDF Report'),
        actions: [
          if (_pdfBytes != null)
            IconButton(
              icon: const Icon(Icons.share),
              onPressed: () => Printing.sharePdf(
                bytes: _pdfBytes!,
                filename: 'sleep_apnea_report.pdf',
              ),
            ),
        ],
      ),
      body: _isGenerating
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 16),
                  Text('Generating PDF report...'),
                ],
              ),
            )
          : PdfPreview(
              build: (_) async => _pdfBytes!,
              allowSharing:  true,
              allowPrinting: true,
              canChangePageFormat: false,
              initialPageFormat: PdfPageFormat.a4,
            ),
    );
  }
}
